googleapis/python-spanner-sqlalchemy

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- test/test_suite.py
The PR requires changes of the [#277](https://github.com/googleapis/python-spanner/pull/277) to be merged first.
> feat: tweak table dropping mechanism

- setup.py
The dialect executes DDL statements separated by `;`. This feature was released in [python-spanner v.3.3.0](https://github.com/googleapis/python-spanner/releases/tag/v3.3.0), so the version of the python-spanner required by the dialect must be at least 3.3.0.
> feat: set higher python-spanner requirements

- google/cloud/sqlalchemy_spanner/requirements.py
- test/test_suite.py
Spanner doesn't support temporary tables. The same tests (for indexes, table names, etc.) are passing on real tables, so these tests can be skipped.
> test: skip unsupported features tests

- create_test_database.py
This PR introduces
- Create instance with unique instance.
- Add labels including time of instance creation.
- Clean old instances erroneously left from failed system test run
> ci: delete old instances

- noxfile.py
- test_migration_env.py
Adding a test session with a minimal migration.
> test: add a migration nox testing session

- noxfile.py
We talked about it some time ago - there is no need in explicit `sqlalchemy` and `google-cloud-spanner` installations, as `session.install("-e", ".")` will do the job.
> test: erase excess installation commands

- README.md
- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- test/test_suite.py
Adding two dialect-specific arguments:
`spanner_interleave_in` - a name of a parent table
`spanner_inverleave_on_delete_cascade` - a flag indicating if `ON DELETE CASCADE` statement should be added for this inverleave relation
> feat: support interleaved tables feature

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- test/test_suite.py
Fixes #98 
- [*] Tests pass
- [*] Appropriate changes to README are included in PR
> fix: correct typo in spanner_interleave_on_delete_cascade keyword

- .github/sync-repo-settings.yaml
This repo does not use Kokoro for presubmits, so it needs a set of requiredStatusCheckContexts different from [the default](https://github.com/googleapis/repo-automation-bots/blob/21bd620e5e09f3bc6e98995bcd1bce6c9c9ee51a/packages/sync-repo-settings/src/required-checks.json#L45-L48) for Python.
> chore: create sync-repo-settings

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- test/test_suite.py
> fix: array columns reflection

- create_test_database.py
- test/benchmark.py
Benchmark has been updated to:
- Use same generated IDs for each run so there are no timing differences related to splits
- Use placeholders for Spanner's `insert_many_rows` to ensure the backend request is the same as SQLAlchemy
There are also changes to improve the usability of the script i.e.instance and database setup will now include creation or recreation as needed.
> chore: update benchmark to better compare performance

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- test/test_suite.py
Cloud Spanner does not support OFFSET without LIMIT so LIMIT is added. This LIMIT should be as large as possible.
The maximum value for LIMIT and OFFSET is their combined value (Limit+Offset). The combined value must be less than or equal to INT64MAX.
> fix: calculate limit value correctly for offset only queries

- BENCHMARKS.md
Results using `google-cloud-spanner==3.12.0`
> docs: update benchmarks

- README.md
- setup.cfg
- setup.py
- version.py
> chore: setup release 1.0.0

- setup.py
The [3.12.0](https://github.com/googleapis/python-spanner/releases/tag/v3.12.0) version of the `google-cloud-spanner` is required, as it includes the last JSON relates changes.
Closes #168
> fix: bump up google-cloud-spanner required version

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- test/test_suite.py
> fix: connection reset fails when an additional dialect is used

- .kokoro/release.sh
- .kokoro/release/common.cfg
This PR pulls in changes from https://github.com/googleapis/synthtool/pull/1327 as we have migrated from secret manager to keystore for publishing to PyPI.
> build(python): switch back to keystore for publication

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
> fix: don't reset attributes of non-Spanner connections

- README.md
- test_migration_env.py
> fix: alembic migration fails in case of a sequential upgrade

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- noxfile.py
> fix: update dialect name for ALTER operation overrides

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- test/test_suite_13.py
- test/test_suite_14.py
Towards #231 
SQLAlchemy introspection method returns all the indexes, including those managed by Spanner internally. As any manipulations with indexes auto managed by Spanner can cause troubles, it's fair to prevent dialect from noticing these indexes. Fortunately, `information_schema` includes a flag, which makes it easy.
> fix: Spanner auto managed indexes should not be introspected

- README.rst
- create_test_database.py
- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- test/test_suite_13.py
- test/test_suite_14.py
Closes #248
Requires `python-spanner` to be released with these two PRs:
https://github.com/googleapis/python-spanner/pull/834
https://github.com/googleapis/python-spanner/pull/838
> feat: support request priorities

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
> fix: introspect constraints, keeping their order

- google/cloud/sqlalchemy_spanner/requirements.py
- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- noxfile.py
- test.cfg
- test/test_suite_13.py
- test/test_suite_14.py
- test/test_suite_20.py
The following PR adds support for the new version of SqlAlchemy 2.0 which has been supported. The PR provides minimal support of feature which were previously supported for SqlAlchemy 1.3 and 1.4 along with a few new functionalities as provided below:
1. Support Views
2. Support getting table info for specific schemas
3. Get view definition
4. Get multi columns
5. Get multi indexes
6. Get multi PK constraint
7. Get multi foreign keys
8. Modify table names in tests to not get view info for emulator
9. Adding test suite for 2.0 support
Along with this, we will now run SqlAlchemy 2.0 as a system test for pre-submits.
> feat:  feat: SQLAlchemy 2.0 support

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- test/test_suite_20.py
> chore: fix build and lint errors

- google/cloud/sqlalchemy_spanner/_opentelemetry_tracing.py
When db.params are not all of the same type OpenTelemetry will log a warning.
Prevent this by stringifying values.
Also adds a  SQLALCHEMY_SPANNER_TRACE_HIDE_QUERY_PARAMETERS env var to prevent logging db.params to OpenTelemetry.
Fixes #345
> fix: db.params OpenTelemetry integration issue

- .github/sync-repo-settings.yaml
- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- noxfile.py
- test/conftest.py
- test/test_suite_20.py
There are couple of changes in this PR to fix this repo pipeline which is failing from last 3 months:
1) Spanner doesn't supports inserting 2 rows (a row with NULL value and a row with some value for a given datatype) for a table with empty primary key. SqlAlchemy added tests couple of months back to insert 2 such rows for different datatypes columns so those tests started failing for this repo.
Fixing to override those tests so as not to insert a row with NULL value but just a single row for each datatype
2) tests: remove editable install in tests 
3) accommodate NULL at the compiler level for literal_render. Please see https://github.com/sqlalchemy/sqlalchemy/commit/1a23c8dee5665ebda75a1ea7d5e7ca355ea1f78b where are copying changes from compiler.py
> fix: Fixing test for literals due to change in sqlalchemy core tests

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
Modify information_schema queries so these are able to handle databases that contain multiple schemas.
> chore: support named schemas

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
https://github.com/googleapis/python-spanner-sqlalchemy/issues/349
> fix: Table name should be quoted by back quotes (`) on DROP TABLE

- samples/partitioned_dml_sample.py
- test/mockserver_tests/mock_server_test_base.py
- test/mockserver_tests/mock_spanner.py
- test/mockserver_tests/test_basics.py
Adds tests and samples for executing Partitioned DML using SQLAlchemy.
Fixes #496
> feat: support Partitioned DML

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- test/mockserver_tests/mock_server_test_base.py
- test/mockserver_tests/test_basics.py
> fix: map now() to current_timestamp

- README.rst
Cleans up the Transaction section of the README file a bit.
> docs: cleanup the transaction section of README a bit

- test/mockserver_tests/mock_server_test_base.py
- test/mockserver_tests/test_basics.py
- test/mockserver_tests/test_read_only_transaction.py
- test/mockserver_tests/test_stale_reads.py
Spanner now supports FOR UPDATE clauses. This change adds a test to verify that FOR UPDATE clauses can be generated with the Spanner SQLAlchemy provider.
See also https://cloud.google.com/spanner/docs/release-notes#January_27_2025
cc @skuruppu
> docs: add test for using FOR UPDATE

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
Fixes a tiny issue in the FK metadata query, where the JOIN condition used the `table_catalog` instead of `constraint_catalog`. This difference does not really have an actual impact, as the catalog is always the same, but this makes the code look more consistent.
> chore: make the fk query joins consistent

- README.rst
- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- samples/model.py
- test/mockserver_tests/commit_timestamp_model.py
- test/mockserver_tests/test_commit_timestamp.py
- test/system/test_basics.py
Add support for columns with commit timestamps:
https://cloud.google.com/spanner/docs/commit-timestamp
Fixes: #695
> feat: support commit timestamp option

- google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py
- samples/null_filtered_index.py
- test/mockserver_tests/null_filtered_index.py
- test/mockserver_tests/test_null_filtered_index.py
Add support for the NULL FILTERED index option:
https://cloud.google.com/spanner/docs/secondary-indexes#null-indexing-disable
Fixes #749
> feat: Support NULL FILTERED indexes

- .github/workflows/test_suite.yml
- migration_test_cleanup.py
- noxfile.py
- Remove all tests with Python 3.8 and replace them with test runs with 3.12.
- Remove all tests with SQLAlchemy 1.3, as that version is no longer supported.
> build: update default python version to 3.12
